defmodule Mix.Tasks.Brand.Gen do
  @moduledoc """
  Regenerates derived brand assets from the single source of truth, `brand/tokens/tokens.json`.

  This is a **dev-only convenience task**. The generated files are committed, so the
  repository renders on GitHub without anyone running this. Run it only after editing
  `brand/tokens/tokens.json`.

      mix brand.gen          # regenerate tokens.css + tailwind.tokens.js
      mix brand.gen --check  # verify committed outputs match the source (CI / QA gate)

  Outputs:

    * `brand/tokens/tokens.css`          — :root custom properties (raw + semantic), light + dark
    * `brand/tokens/tailwind.tokens.js`  — tailwind `theme.extend` excerpt

  Not added to `mix.exs` :package files — brand assets live in git, never in the Hex tarball.
  """
  @shortdoc "Regenerate brand tokens.css + tailwind excerpt from tokens.json"

  use Mix.Task

  @tokens_path "brand/tokens/tokens.json"
  @css_path "brand/tokens/tokens.css"
  @tailwind_path "brand/tokens/tailwind.tokens.js"

  @impl Mix.Task
  def run(args) do
    check? = "--check" in args
    tokens = @tokens_path |> File.read!() |> JSON.decode!()

    outputs = [
      {@css_path, build_css(tokens)},
      {@tailwind_path, build_tailwind(tokens)}
    ]

    if check? do
      drift =
        Enum.filter(outputs, fn {path, content} ->
          case File.read(path) do
            {:ok, existing} -> existing != content
            _ -> true
          end
        end)

      if drift == [] do
        Mix.shell().info("brand.gen --check: OK (#{length(outputs)} files match source)")
      else
        paths = drift |> Enum.map(&elem(&1, 0)) |> Enum.join(", ")
        Mix.raise("brand.gen --check: STALE — run `mix brand.gen`. Out of date: #{paths}")
      end
    else
      Enum.each(outputs, fn {path, content} -> File.write!(path, content) end)
      Mix.shell().info("brand.gen: wrote #{@css_path} and #{@tailwind_path}")
    end
  end

  # ── CSS ──────────────────────────────────────────────────────────────────

  defp build_css(t) do
    raw = Map.fetch!(t, "raw")
    light = get_in(t, ["semantic", "light"])
    dark = get_in(t, ["semantic", "dark"])

    raw_vars =
      raw
      |> sorted()
      |> Enum.map_join("\n", fn {k, v} -> "  --rendro-#{k}: #{v};" end)

    light_vars = semantic_block(light, raw)
    dark_vars = semantic_block(dark, raw)
    scale_vars = scale_block(t)

    """
    /* Rendro design tokens — GENERATED by `mix brand.gen`. Edit brand/tokens/tokens.json, not this file. */

    :root {
      /* Raw palette (primitives) */
    #{raw_vars}

      /* Semantic roles — light (default) */
    #{light_vars}

    #{scale_vars}
    }

    /* Dark mode follows the OS unless an explicit data-theme is set. */
    @media (prefers-color-scheme: dark) {
      :root:not([data-theme="light"]) {
        /* Semantic roles — dark */
    #{indent(dark_vars, "    ")}
      }
    }

    /* Explicit opt-in always wins over the OS preference. */
    [data-theme="dark"] {
    #{indent(dark_vars, "  ")}
    }

    @media (prefers-reduced-motion: reduce) {
      :root {
        --rendro-motion-micro: 0ms;
        --rendro-motion-panel: 0ms;
        --rendro-motion-diagram: 0ms;
      }
    }
    """
  end

  defp semantic_block(map, raw) do
    map
    |> sorted()
    |> Enum.map_join("\n", fn {role, val} ->
      "  --rendro-#{role}: #{resolve_css(val, raw)};"
    end)
  end

  defp scale_block(t) do
    fam = get_in(t, ["type", "family"])

    families = [
      "  --rendro-font-sans: #{fam["sans"]};",
      "  --rendro-font-mono: #{fam["mono"]};",
      "  --rendro-font-fallback: #{fam["fallback"]};"
    ]

    type =
      t["type"]["scale"]
      |> sorted()
      |> Enum.flat_map(fn {name, %{"size" => s, "line" => l, "weight" => w}} ->
        [
          "  --rendro-font-size-#{name}: #{s};",
          "  --rendro-line-#{name}: #{l};",
          "  --rendro-weight-#{name}: #{w};"
        ]
      end)

    space =
      t["space"]
      |> sorted_numeric()
      |> Enum.map(fn {k, v} -> "  --rendro-space-#{k}: #{v};" end)

    radius = simple_vars(t["radius"], "radius")
    border = simple_vars(t["border"], "border")
    shadow = simple_vars(t["shadow"], "shadow")
    grid = simple_vars(t["grid"], "grid")
    state = simple_vars(t["state"], nil)

    motion =
      t["motion"]
      |> Map.take(["micro", "panel", "diagram"])
      |> sorted()
      |> Enum.map(fn {k, v} -> "  --rendro-motion-#{k}: #{v};" end)

    easing = ["  --rendro-easing: #{t["motion"]["easing"]};"]

    [
      "  /* Typography */",
      families,
      type,
      "",
      "  /* Spacing */",
      space,
      "",
      "  /* Radius / border / shadow / motion / grid / state */",
      radius,
      border,
      shadow,
      motion,
      easing,
      grid,
      state
    ]
    |> List.flatten()
    |> Enum.join("\n")
  end

  defp simple_vars(map, prefix) do
    map
    |> sorted()
    |> Enum.map(fn {k, v} ->
      name = if prefix, do: "#{prefix}-#{k}", else: k
      "  --rendro-#{name}: #{v};"
    end)
  end

  # ── Tailwind excerpt ─────────────────────────────────────────────────────

  defp build_tailwind(t) do
    raw = Map.fetch!(t, "raw")
    light = get_in(t, ["semantic", "light"])

    raw_colors =
      raw
      |> sorted()
      |> Enum.map_join("\n", fn {k, v} -> "        #{js_key(k)}: #{js_str(v)}," end)

    # Semantic colors map to CSS vars so dark mode flows through the cascade.
    semantic_colors =
      light
      |> sorted()
      |> Enum.map_join("\n", fn {role, _v} ->
        "        #{js_key(role)}: #{js_str("var(--rendro-#{role})")},"
      end)

    sans = split_stack(get_in(t, ["type", "family", "sans"]))
    mono = split_stack(get_in(t, ["type", "family", "mono"]))

    font_size =
      t["type"]["scale"]
      |> sorted()
      |> Enum.map_join("\n", fn {name, %{"size" => s, "line" => l, "weight" => w}} ->
        "        #{js_key(name)}: [#{js_str(s)}, { lineHeight: #{js_str(l)}, fontWeight: #{js_str(to_string(w))} }],"
      end)

    spacing =
      t["space"]
      |> sorted_numeric()
      |> Enum.map_join("\n", fn {k, v} -> "        #{js_key(k)}: #{js_str(v)}," end)

    radius =
      t["radius"]
      |> sorted()
      |> Enum.map_join("\n", fn {k, v} -> "        #{js_key(k)}: #{js_str(v)}," end)

    """
    /* Rendro Tailwind tokens — GENERATED by `mix brand.gen`. Edit brand/tokens/tokens.json. */
    /* Usage: const rendro = require('./brand/tokens/tailwind.tokens.js'); then spread rendro.theme.extend */
    module.exports = {
      theme: {
        extend: {
          colors: {
    #{raw_colors}
    #{semantic_colors}
          },
          fontFamily: {
            sans: [#{sans}],
            mono: [#{mono}],
          },
          fontSize: {
    #{font_size}
          },
          spacing: {
    #{spacing}
          },
          borderRadius: {
    #{radius}
          },
        },
      },
    };
    """
  end

  # ── helpers ──────────────────────────────────────────────────────────────

  defp resolve_css(val, raw) when is_binary(val) do
    case Regex.run(~r/^\{(.+)\}$/, val) do
      [_, ref] ->
        unless Map.has_key?(raw, ref), do: Mix.raise("Unknown raw token alias: {#{ref}}")
        "var(--rendro-#{ref})"

      _ ->
        val
    end
  end

  defp split_stack(stack) do
    stack
    |> String.split(",")
    |> Enum.map(&String.trim/1)
    |> Enum.map_join(", ", &js_str(String.trim(&1, "'")))
  end

  defp js_key(k), do: "'#{k}'"
  defp js_str(v), do: "'#{v}'"

  defp sorted(map), do: Enum.sort_by(map, fn {k, _} -> k end)
  defp sorted_numeric(map), do: Enum.sort_by(map, fn {k, _} -> String.to_integer(k) end)

  defp indent(block, pad) do
    block
    |> String.split("\n")
    |> Enum.map_join("\n", fn line -> if line == "", do: line, else: pad <> line end)
  end
end
