if Code.ensure_loaded?(Accrue) do
  defmodule Rendro.Adapters.Accrue do
    @moduledoc """
    Optional Accrue billing-document recipe that transforms an
    `Accrue.Invoice` struct into a `Rendro.Document` ready to be passed to
    `Rendro.render/1`.

    This module is only compiled when `Accrue` is available at compile
    time (via `Code.ensure_loaded?/1`). If `:accrue` is not in your
    project's dependencies, this module is absent and core Rendro is
    unaffected.

    ## Usage

        invoice = MyApp.Billing.fetch_invoice!(invoice_id)
        {:ok, doc} = Rendro.Adapters.Accrue.recipe(invoice)
        {:ok, pdf} = Rendro.render(doc)

    ## Contract

    Accepts an `%Accrue.Invoice{}` with the following fields read by the
    recipe:

      * `:id` — invoice identifier rendered as the document title
      * `:customer` — map or struct with at least a `:name` (used in header)
      * `:line_items` — list of `%Accrue.LineItem{}` with `:description`,
        `:quantity`, `:unit_amount`, `:subtotal`
      * `:total` — integer or Decimal-like value rendered in the totals row
      * `:issued_at` — Date/DateTime rendered next to the title

    Unrecognized inputs return `{:error, {:invalid_invoice, value}}`.

    ## Errors

    Returns `{:error, {:invalid_invoice, term()}}` for non-`%Accrue.Invoice{}`
    inputs. The recipe itself does not call `Rendro.render/1`; callers
    compose the recipe result with `Rendro.render/1` so render-time
    policies (max pages/bytes/timeout) and error tuples flow through the
    normal pipeline.
    """

    @spec recipe(term()) ::
            {:ok, Rendro.Document.t()} | {:error, {:invalid_invoice, term()}}
    def recipe(%Accrue.Invoice{} = invoice) do
      header = build_header(invoice)
      content = build_content(invoice)
      footer = build_footer(invoice)

      doc =
        Rendro.flow(content,
          header: header,
          footer: footer
        )

      {:ok, doc}
    end

    def recipe(other), do: {:error, {:invalid_invoice, other}}

    defp build_header(%Accrue.Invoice{id: id, issued_at: issued_at, customer: customer}) do
      [
        Rendro.block(Rendro.text("INVOICE ##{id}", size: 18)),
        Rendro.block(Rendro.text("Issued: #{inspect(issued_at)}", size: 10)),
        Rendro.block(Rendro.text("Bill to: #{customer_name(customer)}", size: 10))
      ]
    end

    defp build_content(%Accrue.Invoice{line_items: line_items, total: total}) do
      rows =
        Enum.map(line_items || [], fn %Accrue.LineItem{} = item ->
          [
            to_string(item.description),
            to_string(item.quantity),
            format_amount(item.unit_amount),
            format_amount(item.subtotal)
          ]
        end)

      table =
        Rendro.table(rows,
          header: ["Description", "Qty", "Unit", "Subtotal"],
          columns: [{:share, 1}, {:fixed, 40}, {:fixed, 60}, {:fixed, 60}]
        )

      [
        Rendro.block(table),
        Rendro.block(Rendro.text("Total: #{format_amount(total)}", size: 12))
      ]
    end

    defp build_footer(%Accrue.Invoice{}) do
      [Rendro.block(Rendro.text("Generated by Rendro + Accrue", size: 8))]
    end

    defp customer_name(%{name: name}) when is_binary(name), do: name
    defp customer_name(_), do: "(unknown)"

    defp format_amount(nil), do: ""
    defp format_amount(value) when is_integer(value), do: "$#{value}"
    defp format_amount(value), do: to_string(value)
  end
end
