defmodule Mix.Tasks.RendroGenThemeTest do
  use ExUnit.Case, async: false

  alias Mix.Tasks.Rendro.Gen.Theme

  test "generates the fixed default wrapper from closed CLI input" do
    with_tmp_dir(fn tmp_dir ->
      {messages, result} =
        capture_shell_messages(fn ->
          Theme.run(["swiss", "--accent", "#2C6BED"])
        end)

      assert result == :ok

      path = Path.join(tmp_dir, "lib/rendro/rendro_theme.ex")
      source = File.read!(path)

      assert source =~ "Generated by: mix rendro.gen.theme swiss --accent #2C6BED --mode light"
      assert source =~ "defmodule Rendro.RendroTheme do"
      assert source =~ "@moduledoc false"
      assert source =~ "def theme do"
      assert source =~ "def register_fonts(document)"
      refute source =~ "def theme("
      refute source =~ "def register_fonts(document,"
      assert Enum.join(messages, "\n") =~ "Generated"

      assert [{Rendro.RendroTheme, _}] = Code.compile_string(source)

      # The generated module exists only after Code.compile_string/1 above, so a
      # direct remote call would create a compile-time undefined-module warning.
      # credo:disable-for-next-line Credo.Check.Refactor.Apply
      assert apply(Rendro.RendroTheme, :theme, []) ==
               Rendro.Theme.preset(:swiss, accent: {44, 107, 237}, mode: :light)
    end)
  end

  test "derives only safe aliases and paths before generating formatter source" do
    with_tmp_dir(fn tmp_dir ->
      source_path = "themes/company_theme.ex"

      Theme.run([
        "humanist",
        "--accent",
        "#147A4B",
        "--mode",
        "dark",
        "--module",
        "MyApp.Brand.CompanyTheme",
        "--out",
        source_path
      ])

      source = File.read!(Path.join(tmp_dir, source_path))
      assert source =~ "defmodule MyApp.Brand.CompanyTheme do"
      assert source =~ "mode: :dark"
      assert source =~ "Presets.register_fonts(document, :humanist)"

      for args <- [
            ["unknown", "--accent", "#2C6BED"],
            ["swiss", "--accent", "#ffffff"],
            ["swiss", "--accent", "#2C6BED", "--mode", "sepia"],
            ["swiss", "--accent", "#2C6BED", "--module", "unsafe.module"],
            ["swiss", "--accent", "#2C6BED", "--out", "../escape.ex"],
            ["swiss", "--accent", "#2C6BED", "--out", "/tmp/escape.ex"],
            ["swiss", "--accent", "#2C6BED", "--unknown"],
            ["swiss", "extra", "--accent", "#2C6BED"],
            ["swiss", "--accent", "#2C6BED", "--check", "--force"]
          ] do
        error = assert_raise Mix.Error, fn -> Theme.run(args) end
        assert error.message =~ "Invalid"
        assert error.message =~ "Next: mix rendro.gen.theme"
      end

      refute File.exists?(Path.join(tmp_dir, "escape.ex"))
    end)

    source = File.read!("lib/mix/tasks/rendro/gen/theme.ex")
    refute source =~ "String.to_atom"
    refute source =~ "Module.concat"
  end

  test "uses Mix conflict handling and keeps check mode read-only" do
    with_tmp_dir(fn tmp_dir ->
      args = ["swiss", "--accent", "#2C6BED", "--out", "lib/generated_theme.ex"]
      path = Path.join(tmp_dir, "lib/generated_theme.ex")

      Theme.run(args)
      generated = File.read!(path)

      Theme.run(args)
      assert File.read!(path) == generated

      File.write!(path, "# detached application policy\n")

      {conflict_messages, :ok} =
        capture_shell_messages(fn ->
          send(self(), {:mix_shell_input, :yes?, false})
          Theme.run(args)
        end)

      assert Enum.join(conflict_messages, "\n") =~ "Skipped lib/generated_theme.ex"
      assert File.read!(path) == "# detached application policy\n"

      Theme.run(args ++ ["--force"])
      assert File.read!(path) == generated

      before_equal = File.stat!(path)
      {messages, :ok} = capture_shell_messages(fn -> Theme.run(args ++ ["--check"]) end)
      assert Enum.join(messages, "\n") =~ "--check: OK"
      assert File.read!(path) == generated
      assert File.stat!(path).mtime == before_equal.mtime

      File.write!(path, "# drift\n")
      before_drift = File.stat!(path)
      drift_error = assert_raise Mix.Error, fn -> Theme.run(args ++ ["--check"]) end
      assert drift_error.message =~ "bytes differ"
      assert drift_error.message =~ "Next: mix rendro.gen.theme"
      assert File.read!(path) == "# drift\n"
      assert File.stat!(path).mtime == before_drift.mtime

      missing_path = Path.join(tmp_dir, "missing/nested/theme.ex")

      missing_error =
        assert_raise Mix.Error, fn ->
          Theme.run([
            "swiss",
            "--accent",
            "#2C6BED",
            "--out",
            "missing/nested/theme.ex",
            "--check"
          ])
        end

      assert missing_error.message =~ "file is missing"
      refute File.exists?(missing_path)
      refute File.exists?(Path.dirname(missing_path))
    end)
  end

  defp with_tmp_dir(fun) do
    tmp_dir =
      Path.join(System.tmp_dir!(), "rendro-gen-theme-#{System.unique_integer([:positive])}")

    File.mkdir_p!(tmp_dir)

    try do
      File.cd!(tmp_dir, fn -> fun.(tmp_dir) end)
    after
      File.rm_rf!(tmp_dir)
    end
  end

  defp capture_shell_messages(fun) do
    original_shell = Mix.shell()
    Mix.shell(Mix.Shell.Process)

    result =
      try do
        fun.()
      after
        Mix.shell(original_shell)
      end

    {flush_shell_messages([]), result}
  end

  defp flush_shell_messages(messages) do
    receive do
      {:mix_shell, _level, payload} ->
        flush_shell_messages([IO.iodata_to_binary(payload) | messages])
    after
      0 -> Enum.reverse(messages)
    end
  end
end
