defmodule Rendro.EdgeMatrixTest do
  use ExUnit.Case, async: true

  # ---------------------------------------------------------------------------
  # EDGE-01 — the family × stress-dimension matrix (D-01).
  #
  # This module is the single, honest source of truth for which
  # {family, dimension} pairs Rendro exercises under stress. Every one of the
  # 102 pairs (17 dimensions × 6 families) has an explicit @matrix entry — either
  # the atom `:applies` (a real golden-verified render) or a human-readable
  # reason string explaining why the pair is genuinely N/A. A coverage gap can
  # never masquerade as coverage: the D-02 meta-test below machine-checks
  # @matrix's exhaustiveness against the cross product @families × @dimensions,
  # so a future new family or dimension that lacks an entry fails immediately.
  # ---------------------------------------------------------------------------

  @families [:invoice, :statement, :receipt, :certificate, :payslip, :ticket]

  @dimensions [
    :text_wrap,
    :line_items_zero,
    :line_items_one,
    :line_items_few,
    :line_items_page_boundary,
    :line_items_60_plus,
    :missing_optional_fields,
    :money_zero,
    :money_negative_parens,
    :money_large,
    :money_cents_rounding,
    :qty_zero,
    :currency_format,
    :tax_label,
    :pagination_boundary,
    :page_size_a4_letter,
    :odd_even_running_content
  ]

  # Repeated N/A reason strings promoted to attributes so the SAME root cause
  # reads as the byte-identical string everywhere it recurs (e.g. Certificate /
  # Ticket share one reason across all five line-item dimensions).
  @na_cert_no_lineitems "certificate has no repeating line-item list"
  @na_ticket_fixed_grid "placement is a fixed 1-4 entry grid, not a variable line-item list"
  @na_cert_no_money "certificates carry no money"
  @na_ticket_no_money "tickets carry no money field"

  # BYTE-vs-RASTER SPLIT (D-09/D-10) — read before touching goldens:
  # Byte-SHA-256 goldens exist for ALL 62 `:applies` cells and are generated by
  # THIS file (priv/goldens/<family>/<dimension>.sha256). Rendro claims
  # byte-determinism EVERYWHERE, NOT pixel-perfect everywhere. A deliberately
  # CURATED subset of exactly 6 cells ADDITIONALLY gets a pdfium raster ref in
  # test/rendro/adapters/pdfium_raster_snapshot_test.exs (117-06):
  #   • {invoice, statement, payslip} × odd_even_running_content — each fixture
  #     simultaneously covers pagination_boundary + line_items_60_plus + odd/even
  #     physical-page parity (D-10a);
  #   • {certificate} × page_size_a4_letter — both A4 and US Letter renders;
  #   • {invoice} × text_wrap — the extreme-wrap representative.
  # Everything else is byte-checked only; that is the intentional, logged scope
  # of what is NOT raster-checked (the D-10 "what is not pixel-checked is logged"
  # requirement). Each row below is {dimension, [invoice, statement, receipt,
  # certificate, payslip, ticket]} in @families column order.
  @matrix_rows [
    {:text_wrap, [:applies, :applies, :applies, :applies, :applies, :applies]},
    {:line_items_zero,
     [:applies, :applies, :applies, @na_cert_no_lineitems, :applies, @na_ticket_fixed_grid]},
    {:line_items_one,
     [:applies, :applies, :applies, @na_cert_no_lineitems, :applies, @na_ticket_fixed_grid]},
    {:line_items_few,
     [:applies, :applies, :applies, @na_cert_no_lineitems, :applies, @na_ticket_fixed_grid]},
    {:line_items_page_boundary,
     [:applies, :applies, :applies, @na_cert_no_lineitems, :applies, @na_ticket_fixed_grid]},
    {:line_items_60_plus,
     [:applies, :applies, :applies, @na_cert_no_lineitems, :applies, @na_ticket_fixed_grid]},
    {:missing_optional_fields, [:applies, :applies, :applies, :applies, :applies, :applies]},
    {:money_zero,
     [:applies, :applies, :applies, @na_cert_no_money, :applies, @na_ticket_no_money]},
    {:money_negative_parens,
     [
       "Invoice totals (subtotal/tax/discount/total) are non-negative by domain convention; discount is subtracted internally, never modeled as a negative Decimal",
       :applies,
       "Receipt totals model a purchase total, not a signed ledger — no natural negative-amount path",
       @na_cert_no_money,
       "deductions are positive magnitudes subtracted internally (net_pay = gross - deductions); no natural negative-Decimal field",
       @na_ticket_no_money
     ]},
    {:money_large,
     [:applies, :applies, :applies, @na_cert_no_money, :applies, @na_ticket_no_money]},
    {:money_cents_rounding,
     [:applies, :applies, :applies, @na_cert_no_money, :applies, @na_ticket_no_money]},
    {:qty_zero,
     [
       :applies,
       "statement lines have no :qty concept",
       "receipt lines have no :qty concept",
       "certificates carry no money or quantities",
       "payslip earnings/deductions have no :qty concept",
       "tickets carry no money or quantities"
     ]},
    {:currency_format,
     [
       :applies,
       :applies,
       :applies,
       @na_cert_no_money,
       :applies,
       "tickets carry no money field to format"
     ]},
    {:tax_label,
     [
       "Invoice's totals 'Tax' line label is a hardcoded string literal — Invoice has no :labels override support (no label_resolver call)",
       "statement has no tax/charge concept anywhere in its domain (a running-balance ledger has no line-item tax)",
       "Receipt's totals 'Tax' line label is a hardcoded string literal — Receipt has no :labels override support",
       @na_cert_no_money,
       :applies,
       "tickets carry no money or tax concept"
     ]},
    {:pagination_boundary,
     [
       :applies,
       :applies,
       :applies,
       "certificate is a fixed single-page layout with no line-item chunking mechanism",
       :applies,
       "ticket is a fixed single-page/single-box layout — no chunking mechanism"
     ]},
    {:page_size_a4_letter,
     [
       "Invoice hardcodes A4 page geometry as a module attribute (@page_width 595.28) — no :page_size option exists",
       "Statement hardcodes A4 page geometry (@page_width 595.28) — no :page_size option exists",
       "Receipt hardcodes A4 page geometry (@page_width 595.28) — no :page_size option exists",
       :applies,
       :applies,
       :applies
     ]},
    {:odd_even_running_content,
     [
       :applies,
       :applies,
       :applies,
       "certificate is a fixed single-page layout — no second page to differ by parity",
       :applies,
       "ticket is a fixed single-page/single-box layout — no second page to differ by parity"
     ]}
  ]

  # Zip each row's six values against @families in column order into the flat
  # {{family, dimension} => value} map (D-01's locked shape). Structurally, a
  # short/long row would drop or add pairs — which the D-02 meta-test then
  # catches — so this construction and its guard are defense-in-depth.
  @matrix for {dimension, values} <- @matrix_rows,
              {family, value} <- Enum.zip(@families, values),
              into: %{},
              do: {{family, dimension}, value}

  @doc """
  The set of `"family/dimension"` string IDs for every `:applies` matrix cell.

  Public (NOT an ExUnit `test`) so 117-07's rubric-exemption disjointness guard
  (D-15) can import @matrix's `:applies` cells as its single source of truth for
  which fixture IDs count as stress-exempt.
  """
  @spec stress_fixture_ids() :: MapSet.t()
  def stress_fixture_ids do
    @matrix
    |> Enum.filter(fn {_, v} -> v == :applies end)
    |> Enum.map(fn {{family, dim}, _} -> "#{family}/#{dim}" end)
    |> MapSet.new()
  end

  # --- D-02 coverage-honesty meta-test + transcription tripwires ------------

  test "every {family, dimension} pair has a @matrix entry" do
    all_pairs = for f <- @families, d <- @dimensions, do: {f, d}
    missing = all_pairs -- Map.keys(@matrix)

    assert missing == [],
           "coverage gap: these {family, dimension} pairs have no @matrix entry: " <>
             inspect(missing)
  end

  test "the matrix has exactly 102 entries" do
    assert map_size(@matrix) == 102
  end

  test "exactly 62 cells are :applies" do
    assert Enum.count(@matrix, fn {_, v} -> v == :applies end) == 62
  end

  # --- Data-driven golden byte-identity tests (one per :applies cell) --------
  #
  # The `{{family, dimension}, :applies}` pattern filters the comprehension to
  # exactly the 62 `:applies` cells. Each generated test proves two-run
  # determinism BEFORE any hash is taken (D-04), then compares/blesses the
  # SHA-256 against priv/goldens/<family>/<dimension>.sha256. A missing ref
  # hard-flunks (never a silent auto-create). `unquote/1` injects each
  # compile-time comprehension value into the quoted test body.
  for {{family, dimension}, :applies} <- @matrix do
    test "#{family}/#{dimension} golden byte-identity" do
      data_doc = Rendro.Test.EdgeFixtures.document(unquote(family), unquote(dimension))
      pdf = Rendro.Test.Golden.assert_deterministic!(data_doc)
      Rendro.Test.Golden.assert_or_bless({unquote(family), unquote(dimension)}, pdf)
    end
  end
end
