name: Release to Hex

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: '28'
          elixir-version: '1.19.5'

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Install Dependencies
        run: mix deps.get

      - name: Run CI Checks
        run: mix ci

      - name: Run Release Preflight
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: mix release.preflight

      - name: Publish to Hex
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: mix hex.publish --yes
